name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '1,11,21,31,41,51 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        wget http://housing.gatech.edu/rooms/FreeRooms.json -O data/F21-S22/$(date +%s).json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        timestamp_num=$(date +%s)
        git commit -m "Latest data: ${timestamp} (${timestamp_num})" || exit 0
        git push